---
- hosts: jenkins
  user: vagrant
  become: yes
  connection: ssh
  roles:
    - sshkeyjenkins
  tasks:
  - name: Ensure Jenkins Repository is Installed
    yum_repository:
      name: jenkins
      state: present
      description: Official Jenkins Yum Repo
      baseurl: http://pkg.jenkins.io/redhat
      gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      gpgcheck: yes
      enabled: yes
  - name: Ensure Jenkins is Installed
    yum:
      name: jenkins
      update_cache: yes
      state: present
  - name: Ensure git is Installed
    yum:
      name: git
      state: present
  - name: Disable Jenkins setup wizard
    lineinfile:
      path: /etc/sysconfig/jenkins
      regexp: ^JENKINS_JAVA_OPTIONS
      line: JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Djenkins.install.UpgradeWizard.show=false"
  - name: Enable and Start the Jenkins Service
    service:
      name: jenkins
      enabled: yes
      state: started
  - name: Open Firewall Port
    firewalld:
      zone: public
      port: 8080/tcp
      permanent: true
      state: enabled
      immediate: true
  - name: Add httpd service permanently
    firewalld:
      service: https
      permanent: yes
      state: enabled
  - name: Reload firewalld
    command: firewall-cmd --reload

