--- #Master Playbook
- hosts: gitlab
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - gitlab
- hosts: jenkins
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - jenkins
    - sshkeyjenkins
- hosts: rocket
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - rocket
- hosts: vault
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - vault
- hosts: production
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - production
    - sshkeywebapp
- hosts: preprod
  user: vagrant
  sudo: yes
  connection: ssh
  roles:
    - preprod
    - sshkeywebapp
