- name: Ensure Jenkins Repository is Installed
  command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
- name: Import Jenkins CI key
  rpm_key:
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
  #yum_repository:
  #  name: jenkins
  #  state: present
  #  tabkescription: Official Jenkins Yum Repo
  #  baseurl: http://pkg.jenkins.io/redhat-stable/jenkins.repo
  #  gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  #  gpgcheck: yes
  #  enabled: yes
- name: Ensure Jenkins is Installed
  yum:
    name: jenkins
    update_cache: yes
    state: present
    #- name: Disable Jenkins setup wizard
    #lineinfile:
    #path: /etc/sysconfig/jenkins
    #regexp: ^JENKINS_JAVA_OPTIONS
    #line: JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=true"
- name: Enable and Start the Jenkins Service
  become: yes
  service:
    name: jenkins
    enabled: yes
    state: started
- name: Start Firewalld
  become: yes
  service:
    name: firewalld
    state: started
    enabled: yes
- name: Open Firewall Port
  become: yes
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: true
- name: Add httpd service permanently
  become: yes
  firewalld:
    service: https
    permanent: yes
    state: enabled
- name: Reload firewalld
  become: yes
  command: firewall-cmd --reload
- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30
- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
- name: Print init password Jenkins
  debug:
    var: result.stdout
