
---
- name: Set authorized key taken from file
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/home/marcolcal/shadow-project/cicd-Project/.ssh_keys/jenkins.pub') }}"
  tags:
    - sshkeys
