---
- name: create the Mongodb repo service file
  shell: echo -e "[mongodb-org-3.6]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.6/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc" | sudo tee /etc/yum.repos.d/mongodb-org-3.6.repo
- name: install node js via package manager
  shell: sudo yum install -y curl && curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -
- name: Be sure the latest packages are installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc-c++
    - make
    - mongodb-org
    - nodejs
    - epel-release
    - GraphicsMagick
- name: npm install inherits n and node version
  raw: sudo npm install -g inherits n && sudo n 8.11.3
- name: ads the rocketchat group
  group:
    name: rocketchat
    state: present
- name: Adds the rocket chat user
  user:
    name: rocketchat
    group: rocketchat
    password_lock: yes
    create_home: no
- name: download the rocket chat binary
  get_url:
    url: https://releases.rocket.chat/latest/download
    dest: /tmp/rocket.chat.tgz
    owner: rocketchat
    group: rocketchat
    mode: 0755
- name: Extract the rocket chat file
  unarchive:
    src: /tmp/rocket.chat.tgz
    dest: /opt/
    copy: no
    owner: rocketchat
    group: rocketchat
    mode: 0755
    creates: /opt/bundle
- name: npm install cd /tmp/bundle/programs/server && npm install
  shell: cd /opt/bundle/programs/server && sudo npm install
- name: rename the opt file howerver you want it
  shell: sudo cp -R /opt/bundle /opt/Rocket.Chat
- name: Remove bundle
  file: path=/opt/bundle state=absent
- name: rocket chat configuration file
  shell: echo -e "[Unit]\nDescription=The Rocket.Chat server\nAfter=network.target remote-fs.target nss-lookup.target nginx.target mongod.target\n[Service]\nExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js\nStandardOutput=syslog\nStandardError=syslog\nSyslogIdentifier=rocketchat\nUser=rocketchat\nEnvironment=LD_PRELOAD=/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/vendor/lib/libz.so NODE_ENV=production MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://10.2.3.80:3000/ PORT=3000\n[Install]\nWantedBy=multi-user.target" | sudo tee /usr/lib/systemd/system/rocketchat.service
- name: restart mongo and rocket
  shell: sudo systemctl enable mongod && sudo systemctl start mongod
- name: rocket
  shell: sudo systemctl enable rocketchat && sudo systemctl start rocketchat

